/// Provides simple localization without relying on intl packages.
class AppLocalizations {
  final String languageCode;
  AppLocalizations(this.languageCode);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'select_language': 'Select Language',
      'continue': 'Continue',
      'no_language_selected': 'No Language Selected',
      'please_select_language': 'Please select a language to continue.',
      'change_language': 'Change Language',
      'legal': 'Legal',
      'news_feed': 'News Feed',
      'about_us': 'About Us',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'contact': 'Contact',
      'contact_us': 'Contact Us',
      'preferences': 'Preferences',
      'settings': 'Settings',
      'forget_saved_number': 'Forget Saved Number',
      'are_you_sure': 'Are you sure?',
      'remove_saved_number': 'This will remove the saved number from your device.',
      'cancel': 'Cancel',
      'forget': 'Forget',
      'dispatch_qty': 'Dispatched Qty',
      'saved_number_forgotten': 'Saved number has been forgotten.',
      'share_app': 'Share App',
      'app_theme': 'App Theme',
      'system_default': 'System Default',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'select_theme': 'Select Theme',
      'track': 'Track Now',
      'booking': 'Booking',
      'history': 'HISTORY',
      'coming_soon': 'Coming Soon',
      'profile': 'Profile',
      'track_your_luggage': 'TRACK YOUR CARGO HERE',
      'enter_phone_and_code': "Enter phone number",
      'sender_receiver_number': '(sender or receiver number)',
      'please_enter_phone_number': 'Please enter a phone number',
      'code_number': 'Enter Code number',
      'please_enter_tracking_code': 'Please enter the tracking code',
      'save_number_question': 'Save Number?',
      'would_you_like_to_save_number': 'Would you like to save this phone number for next time?',
      'dont_save': "Don't Save",
      'save': 'Save',
      'enter_contact': 'Enter Contact',
      'save_text':'Would you like to save your number for permanent access',
      'checking_package': 'Checking your package...',
      'no_cargo_found': 'No cargo found',
      'quick_check': 'Quick check',
      'cargo_details': 'Cargo Details',
      'out': 'out',
      'List_cargo': 'Liste des cargaisons associées à',
      'store': 'store',
      'dispatch_info': 'Dispatch Info',
      'dispatch_date': 'Dispatch Date',
      'date_registerd': 'Date Registered',
      'dispatch_status': 'Dispatch Status',
      'cargo_id': 'Cargo ID',
      'cargo_info': 'Cargo Information',
      'registered': 'Registered',
      'sender': 'Sender Name',
      'sender_no': 'Sender No',
      'receiver': 'Receiver Name',
      'receiver_no': 'Receiver No',
      'quantity': 'Quantity',
      'payment_option': 'Payment Mode',
      'paid_price': 'Paid',
      'to_be_paid_price': 'To be paid ',
      'total_price': 'Total Price',
      'tracking_history': 'Tracking History',
      'status': 'Status',
      'introduction': 'INTRODUCTION',
      'price_list': 'PRICE LIST',
      'route': 'Route',
      'enter_your_contact': 'Enter your contact',
      'email_phone':'Email Or Phone number',
      'paid': 'Paid',
      'back': 'back',
      'price': 'Price',
      'check_up': 'Check up with our lates news',
      'catch': 'Catch up our new feed',
      'read_more': 'Read more...',
      'contact_text': "Feel free to contact our office  For instant and quick response  you can also chat with us Direct  by sending us your sms on this app ",
      'comment': 'Enter your comment',
      'leave_comment': 'Leave us your comment',
      'comment_name': 'Comment',
      'coming': 'Coming Soon',

      'about_us_content':
          'SR Classic coach is a Tanzanian based company which deals with road transportation of passengers and cargo across East and Central Africa. '
          'SR Classic coach operates in 7 countries including Tanzania, Kenya, Uganda, Burundi, Zambia, Zimbabwe and Democratic Republic of Congo with over 150 fleet of buses and over 1000 staff and operators.\n\n'
          'The company provides service of transporting people and goods from Dar es Salaam to Lubumbashi, Lusaka, Harare, Kampala, Bujumbura, and more route connections in Kenya, Uganda and DRC Congo to local cities and neighboring countries.',
    },
    'sw': {
      'select_language': 'Chagua Lugha',
      'List_cargo': 'Idadi ya mizigo inayohusiana na hii namba',
      'continue': 'Endelea',
      'leave_comment': 'Tuachie maoni yako',
      'coming': 'Itakuja Karibuni',

      'no_language_selected': 'Hakuna Lugha Imechaguliwa',
      'please_select_language': 'Tafadhali chagua lugha kuendelea.',
      'change_language': 'Badilisha Lugha',
      'legal': 'Kisheria',
      'news_feed': 'Habari',
      'check_up': 'Angalia Habari zetu',
      'about_us': 'Kuhusu Sisi',
      'privacy_policy': 'Sera ya Faragha',
      'terms_of_service': 'Sheria na Masharti',
      'contact': 'Mawasiliano',
      'enter_contact': 'Weka Maoni yako',
      'email_phone':'Barua bebe au namba ya simu',
      'contact_us': 'Wasiliana Nasi',
      'preferences': 'Mapendeleo',
      'settings': 'Mipangilio',
      'forget_saved_number': 'Sahau Nambari Iliyohifadhiwa',
      'are_you_sure': 'Una uhakika?',
      'remove_saved_number': 'Hii itaondoa nambari iliyohifadhiwa kwenye kifaa chako.',
      'cancel': 'Ghairi',
      'forget': 'Sahau',
      'dispatch_qty': 'Kiasi kilicho enda',
      'back': 'Nyuma',
      'saved_number_forgotten': 'Nambari iliyohifadhiwa imesahaulika.',
      'share_app': 'Shiriki Programu',
      'app_theme': 'Mandhari ya Programu',
      'system_default': 'Mfumo Chaguomsingi',
      'light_mode': 'Mwanga',
      'dark_mode': 'Giza',
      'select_theme': 'Chagua Mandhari',
      'track': 'Fuata',
      'booking': 'Booking',
      'history': 'Historia',
      'coming_soon': 'Inakuja Hivi Karibuni',
      'profile': 'Wasifu',
      'track_your_luggage': 'Fuatilia Mzigo Yako',
      'enter_phone_and_code': '* Ingiza nambari ya simu na nambari ya mzigo kama ilivyo kwenye risiti',
      'sender_receiver_number': '(namba ya mtumaji au mpokeaji)',
      'please_enter_phone_number': 'Tafadhali ingiza nambari ya simu',
      'code_number': 'Nambari ya mzigo',
      'please_enter_tracking_code': 'Tafadhali ingiza nambari ya ufuatiliaji',
      'save_number_question': 'Hifadhi Namba?',
      'would_you_like_to_save_number': 'Je, ungependa kuhifadhi namba hii kwa matumizi yajayo?',
      'dont_save': 'Usihifadhi',
      'save': 'Tunza',
      'save_text':'Unge penda kutunza namba kwa matumzi ya badae',
      'sender_no': 'Number ya mtumaji',
      'checking_package': 'Inaangalia kifurushi chako...',
      'no_cargo_found': 'Hakuna mzigo uliopatikana',
      'quick_check': 'Angalia haraka',
      'cargo_details': 'Maelezo ya Mizigo',
      'out': 'nje',
      'store': 'Store',
      'dispatch_info': 'Taarifa za Usafirishaji',
      'dispatch_date': 'Tarehe ya Usafirishaji',
      'dispatch_status': 'Hali ya Usafirishaji',
      'cargo_id': 'Kitambulisho cha mzigo',
      'cargo_info': 'Taarifa za Mizigo',
      'registered': 'Imesajiliwa',
      'sender': 'Jina la mtumaji',
      'receiver': 'Jina la mpokeaji',
      'quantity': 'Kiasi',
      'payment_option': 'Njia ya Malipo',
      'paid_price': 'Imelipwa',
      'to_be_paid_price': 'Itayolipwa',
      'total_price': 'Jumla',
      'tracking_history': 'Historia ya Ufuatiliaji',
      'status': 'Hali',
      'introduction': 'UTANGULIZI',
      'price_list': 'ORODHA YA BEI',
      'route': 'Njia',
      'price': 'Bei',
      'date_registerd': 'Siku ya kusajiliwa',
      'catch': 'Angalia habari zetu mpya',
      'read_more': 'Soma zaidi...',
      'receiver_no': 'Namba ya mpokeaji',
      'contact_text': "Jisikie huru kuwasiliana na ofisi yetu  Kwa majibu ya papo hapo na ya haraka  unaweza pia kuzungumza nasi Moja kwa moja kwa kututumia sms yako kwenye programu hii",
      'enter_your_contact': 'Weka Mawasiliano yako',
      'comment': 'Weka maoni yako',
      'comment_name': 'Maoni',

      'about_us_content':
          'SR Classic coach ni kampuni ya Tanzania inayojishughulisha na usafiri wa barabara wa abiria na mizigo kote Afrika Mashariki na Kati. '
          'SR Classic coach inafanya kazi katika nchi 7 zikiwemo Tanzania, Kenya, Uganda, Burundi, Zambia, Zimbabwe na Jamhuri ya Kidemokrasia ya Kongo ikiwa na zaidi ya mabasi 150 na wafanyakazi zaidi ya 1000.\n\n'
          'Kampuni hutoa huduma ya kusafirisha watu na mizigo kutoka Dar es Salaam kwenda Lubumbashi, Lusaka, Harare, Kampala, Bujumbura, na njia nyingine katika Kenya, Uganda na DRC Congo kuelekea miji ya ndani na nchi jirani.',
    },
    'fr': {
      'select_language': 'Choisir la langue',
      'continue': 'Continuer',
      'news_feed': "Fil d'actualité",
      'no_language_selected': 'Aucune langue sélectionnée',
      'please_select_language': 'Veuillez sélectionner une langue pour continuer.',
      'change_language': 'Changer de langue',
      'legal': 'Juridique',
      'comment_name': 'Commentaire',
      'coming': 'À venir',

      'contact_text': "N'hésitez pas à contacter notre bureau  Pour une réponse instantanée et rapide  vous pouvez également discuter avec nous directement  en nous envoyant vos SMS sur cette application",
      'enter_contact': 'Entrez le contact',
      'email_phone':'Email ou numéro de téléphone',
      'enter_your_contact': 'Entrez votre contact',
      'date_registerd': 'Date enregistrée',
      'check_up': 'Consultez nos dernières actualités',
      'about_us': 'À propos de nous',
      'leave_comment': 'Laissez-nous votre commentaire',
      'dispatch_qty': 'Quantité expédiée',
      'List_cargo': 'Liste des cargoisons associeesa a',
      'privacy_policy': 'Politique de confidentialité',
      'terms_of_service': "Conditions d'utilisation",
      'contact': 'Contact',
      'contact_us': 'Contactez-nous',
      'preferences': 'Préférences',
      'settings': 'Paramètres',
      'forget_saved_number': 'Oublier le numéro enregistré',
      'are_you_sure': 'Êtes-vous sûr?',
      'remove_saved_number': "Cela supprimera le numéro enregistré de votre appareil.",
      'cancel': 'Annuler',
      'forget': 'Oublier',
      'saved_number_forgotten': 'Le numéro enregistré a été oublié.',
      'share_app': "Partager l'application", 
      'app_theme': "Thème de l'application", 
      'system_default': 'Système par défaut',
      'light_mode': 'Clair',
      'dark_mode': 'Sombre',
      'select_theme': 'Sélectionner le thème',
      'track': 'Suivre',
      'back': 'Dos',
      'booking': 'Réservation',
      'history': 'Historique',
      'coming_soon': 'Bientôt disponible',
      'comment': 'Entrez votre commentaire',
      'profile': 'Profil',
      'track_your_luggage': 'Suivez votre cargaison ici',
      'enter_phone_and_code': "*Entrez le numéro de téléphone de l'expéditeur ou du destinataire",
      'sender_receiver_number': "(numéro de l'expéditeur ou du destinataire)",
      'please_enter_phone_number': 'Veuillez entrer un numéro de téléphone',
      'code_number': 'Numéro de code',
      'please_enter_tracking_code': 'Veuillez entrer le code de suivi',
      'save_number_question': 'Enregistrer le numéro ?',
      'would_you_like_to_save_number': 'Souhaitez-vous enregistrer ce numéro pour la prochaine fois ?',
      'dont_save': 'Ne pas enregistrer',
      'save': 'Enregistrer',
      'save_text':'Souhaitez-vous enregistrer votre numéro pour un accès facile',
      'checking_package': 'Vérification de votre colis...',
      'no_cargo_found': 'Aucun colis trouvé',
      'quick_check': 'Vérification rapide',
      'cargo_details': 'Détails du colis',
      'out': 'sorti',
      'store': 'entrepôt',
      'dispatch_info': "Infos d'expédition",
      'dispatch_date': "Date d'expédition",
      'dispatch_status': "Statut d'expédition",
      'cargo_id': 'ID du colis',
      'cargo_info': 'Infos du colis',
      'registered': 'Enregistré',
      'sender': 'Expéditeur',
      'receiver': 'Destinataire',
      'quantity': 'Quantité',
      'payment_option': 'Option de paiement',
      'paid_price': 'Prix pay\u00e9',
      'to_be_paid_price': 'Prix \u00e0 payer',
      'total_price': 'Prix Total',
      'tracking_history': 'Historique de suivi',
      'status': 'Statut',
      'introduction': 'INTRODUCTION',
      'price_list': 'LISTE DES PRIX',
      'route': 'Itinéraire',
      'price': 'Prix',
      'catch': 'Découvrez notre nouveau flux',
      'read_more': 'En savoir plus..',
      'receiver_no': 'Numéro de récepteur',

      'about_us_content':
          'SR Classic coach est une société tanzanienne qui s\'occupe du transport routier de passagers et de marchandises à travers l\'Afrique de l\'Est et centrale. '
          'SR Classic coach opère dans 7 pays dont la Tanzanie, le Kenya, l\'Ouganda, le Burundi, la Zambie, le Zimbabwe et la République démocratique du Congo avec une flotte de plus de 150 bus et plus de 1000 employés et opérateurs.\n\n'
          'La société assure le transport de personnes et de marchandises de Dar es Salaam vers Lubumbashi, Lusaka, Harare, Kampala, Bujumbura, ainsi que d\'autres liaisons routières au Kenya, en Ouganda et en RDC vers les villes locales et les pays voisins.',
      'sender_no': "numéro d'expéditeur",

    },
  };

  /// Returns the localized value for the given key or the key itself.
  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
